spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xeno_shopify?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Meduvada
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: "super-secret-key-change-this-32charsmin"
  expirationMillis: 86400000
